name: vs_story_designer
description: This is a package created in the style of the instagram story creator, with which you can create images with images, texts, finger drawing.
version: 2.2.0
homepage:  https://github.com/VickySalunkhe/vs_story_designer

environment:
  sdk: '>=2.18.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state management
  provider: ^6.1.1
  # image
  image: ^4.1.4
  path_provider: ^2.1.2
  photo_view: ^0.14.0
  google_fonts: ^6.1.0
  image_gallery_saver: ^2.0.3
  
  vs_media_picker: ^1.0.1
  # gallery_media_picker: 0.0.82

  # modal_gif_picker: ^0.0.2
  # painting
  perfect_freehand: ^2.3.0
  # positioning
  align_positioned: ^4.0.0
  #message
  # fluttertoast: ^8.1.2
  oktoast: ^3.4.0

  # animated_text_kit: ^4.2.2

  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  # dotted_border: ^2.0.0+3



flutter:

  assets:
    - packages/vs_story_designer/assets/icons/align_center.png
    - packages/vs_story_designer/assets/icons/align_left.png
    - packages/vs_story_designer/assets/icons/align_rigth.png
    - packages/vs_story_designer/assets/icons/arrow.png
    - packages/vs_story_designer/assets/icons/brush.png
    - packages/vs_story_designer/assets/icons/check.png
    - packages/vs_story_designer/assets/icons/circular_gradient.png
    - packages/vs_story_designer/assets/icons/colorpalette.png
    - packages/vs_story_designer/assets/icons/download.png
    - packages/vs_story_designer/assets/icons/draft.png
    - packages/vs_story_designer/assets/icons/draw.png
    - packages/vs_story_designer/assets/icons/font_backGround.png
    - packages/vs_story_designer/assets/icons/marker.png
    - packages/vs_story_designer/assets/icons/neon.png
    - packages/vs_story_designer/assets/icons/pen.png
    - packages/vs_story_designer/assets/icons/pickColor.png
    - packages/vs_story_designer/assets/icons/return.png
    - packages/vs_story_designer/assets/icons/stickers.png
    - packages/vs_story_designer/assets/icons/text.png
    - packages/vs_story_designer/assets/icons/trash.png
    - packages/vs_story_designer/assets/icons/photo_filter.png
    - packages/vs_story_designer/assets/icons/video_trim.png
    - packages/vs_story_designer/assets/images/instagram_logo.png

  # fonts:

    # - family: Alegreya
    #   fonts:
    #     - asset: packages/vs_story_designer/assets/fonts/Alegreya-VariableFont_wght.ttf

    # - family: B612
    #   fonts:
    #     - asset: packages/vs_story_designer/assets/fonts/B612-Regular.ttf

    # - family: TitilliumWeb
    #   fonts:
    #     - asset: packages/vs_story_designer/assets/fonts/TitilliumWeb-Regular.ttf

    # - family: Varela
    #   fonts:
    #     - asset: packages/vs_story_designer/assets/fonts/Varela-Regular.ttf

    # - family: Vollkorn
    #   fonts:
    #     - asset: packages/vs_story_designer/assets/fonts/Vollkorn-Regular.ttf

    # - family: Rakkas
    #   fonts:
    #     - asset: packages/vs_story_designer/assets/fonts/Rakkas-Regular.ttf

    # - family: ConcertOne
    #   fonts:
    #     - asset: packages/vs_story_designer/assets/fonts/ConcertOne-Regular.ttf

    # - family: YatraOne
    #   fonts:
    #     - asset: packages/vs_story_designer/assets/fonts/YatraOne-Regular.ttf

    # - family: OldStandardTT
    #   fonts:
    #     - asset: packages/vs_story_designer/assets/fonts/OldStandardTT-Italic.ttf

    # - family: Neonderthaw
    #   fonts:
    #     - asset: packages/vs_story_designer/assets/fonts/Neonderthaw-Regular.ttf

    # - family: DancingScript
    #   fonts:
    #     - asset: packages/vs_story_designer/assets/fonts/DancingScript-VariableFont_wght.ttf

    # - family: SedgwickAve
    #   fonts:
    #     - asset: packages/vs_story_designer/assets/fonts/SedgwickAve-Regular.ttf

    # - family: IndieFlower
    #   fonts:
    #     - asset: packages/vs_story_designer/assets/fonts/IndieFlower-Regular.ttf

    # - family: Sacramento
    #   fonts:
    #     - asset: packages/vs_story_designer/assets/fonts/Sacramento-Regular.ttf

    # - family: PressStart2P
    #   fonts:
    #     - asset: packages/vs_story_designer/assets/fonts/PressStart2P-Regular.ttf

    # - family: FrederickatheGreat
    #   fonts:
    #     - asset: packages/vs_story_designer/assets/fonts/FrederickatheGreat-Regular.ttf

    # - family: ReenieBeanie
    #   fonts:
    #     - asset: packages/vs_story_designer/assets/fonts/ReenieBeanie-Regular.ttf

    # - family: BungeeShade
    #   fonts:
    #     - asset: packages/vs_story_designer/assets/fonts/BungeeShade-Regular.ttf

    # - family: UnifrakturMaguntia
    #   fonts:
    #     - asset: packages/vs_story_designer/assets/fonts/UnifrakturMaguntia-Regular.ttf